name: 'Publish package to GitHub Packages'
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Fetch all tags'
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: 'Set up JDK and Maven'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: 'Publish package with Maven'
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JGITVER_BRANCH: main
